# Automatically generated by GPRPy
import gprpy.gprpy as gp
mygpr = gp.gprpyProfile()
mygpr.importdata('E:/Padova/Software/GPRPy/gprpy/exampledata/GSSI/FILE____032.DZT')
mygpr.alignTraces()
mygpr.setZeroTime(10)
